version: "3.5"

services:
    entorno2:
        build:
            context: .
            args:
                USER_NAME: usuario
                GIT_USER_NAME: "usuario"
                GIT_USER_EMAIL: "usuario@usuario.com"
        image: iochannel/ssh-container:test
        container_name: "ssh_container"
        volumes:
            - ./claves:/generatedKeys
        networks:
            - rundeck
networks:
    rundeck:
        external:   true    
        name:       mi-red
