# Arranque docker-compose up (En nuestro caso hemos creado un init.sh... para permisos de las carpetas)
# Para asegurar el correcto arranque del contenedor: $ docker logs mirundeck

version: "2" # La versión del esquema YAML de docker compose que estamos usando para este documento

services:
    rundeck:
        container_name:     mirundeck
        build: # Genera una imagen de contenedor
            context:        . # En esta carpeta tienes el Dockerfile... y cualquier otro archivo que necesites
            args:
                RUNDECK_IMAGE:  rundeck/rundeck:5.1.0
        image:              rundeck-ansible:5.1.0          
        environment:
            # Esta URL es en la que se ofrece servicio (PUBLICO)
            # Por defecto se ofrece la URL: http://127.0.0.1:440
            # En nuestro caso, al tener en el host una ip de una vpn a la que no tenemos acceso desde cada,
            # usámos una IP Publica que amazon nos suministra y que sacamos de: 
            #  $ curl ifconfig.me
            RUNDECK_GRAILS_URL: "http://${PUBLIC_IP}:4440"
            # En el caso de Amazon... y en otros clouds, tenemos un firewall de red que bloquea las comunicaciones
            # Hay que abrir el puerto (en nuestro caso, deshabilitaremos el forewall porque vamos a montar muchas apps) 
            # EN UN ENTORNO REAL NI DE COÑA !!!
            RUNDECK_DATABASE_URL:           jdbc:mariadb://db:3306/rundeck?autoReconnect=true&useSSL=false
            RUNDECK_DATABASE_USERNAME:      usuario
            RUNDECK_DATABASE_PASSWORD:      password
            RUNDECK_DATABASE_DRIVER:        org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_DIALECT:       org.hibernate.dialect.MariaDBDialect
            # Configuracion email server:
            # https://docs.rundeck.com/docs/administration/configuration/docker.html#security-headers:~:text=for%20CSP%20headers.-,%23,-Email
            RUNDECK_MAIL_SMTP_HOST:         mi-email-server
            RUNDECK_MAIL_SMTP_PORT:         1025

            RUNDECK_JAAS_MODULES_0: JettyCombinedLdapLoginModule
            RUNDECK_JAAS_LDAP_PROVIDERURL: ldap://openldap:389
            RUNDECK_JAAS_LDAP_BINDDN: cn=admin,dc=curso,dc=com
            RUNDECK_JAAS_LDAP_BINDPASSWORD: password
            RUNDECK_JAAS_LDAP_USERBASEDN: ou=users,dc=curso,dc=com
            RUNDECK_JAAS_LDAP_ROLEBASEDN: ou=roles,dc=curso,dc=com
        volumes:
                              - /home/ubuntu/environment/data/rundeck:/home/rundeck/server/data
                              - /home/ubuntu/environment/curso/proyectos/ansible:/home/rundeck/server/data/ansible
        ports:
                              - 4440:4440
        networks:
            - rundeck

    db: # FQDN resoluble en la red de docker 
        container_name:     mimariadb
        image:              mariadb:11.2 # En un momento dado puede apuntar a la 11.2.3 o a la 11.2.5
        environment:
            MARIADB_ROOT_PASSWORD: password
            MARIADB_DATABASE:      rundeck
            MARIADB_USER:          usuario
            MARIADB_PASSWORD:      password
        volumes:
                              - /home/ubuntu/environment/data/mariadb:/var/lib/mysql
        networks:
            - rundeck
    # En: https://github.com/rundeck/docker-zoo/tree/master
    # Teneis ejemplos de configuración de postgresql, mysql, sqlserver y oracle

    mi-email-server: # FQDN resoluble en la red de docker 
        container_name:     mimailhog
        image:              mailhog/mailhog
        ports:
                          # Trabaja en el puerto 1025... pero no lo exponemos... no nos hace falta
                          - 8080:8025
        networks:
                          - rundeck



    openldap:
        image: osixia/openldap:1.2.1
        container_name: openldap
        environment:
            LDAP_ORGANISATION: Curso
            LDAP_DOMAIN: curso.com
            LDAP_ADMIN_PASSWORD: password
            LDAP_TLS: "false"
            LDAP_TLS_ENFORCE: "false"
            LDAP_TLS_VERIFY_CLIENT: "never"
        tty: true
        stdin_open: true
        command: --copy-service
        volumes:
          - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom:rw
        domainname: "rundeck.com" 
        hostname: "ldap.rundeck.com"
        networks:
                          - rundeck

    phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: phpldapadmin
        environment:
          PHPLDAPADMIN_LDAP_HOSTS: "openldap"
          PHPLDAPADMIN_HTTPS: "false"
        ports:
          - "8081:80"
        depends_on:
          - openldap
        networks:
                          - rundeck

networks:
    rundeck:
        name: mi-red