# Arranque docker-compose up (En nuestro caso hemos creado un init.sh... para permisos de las carpetas)
# Para asegurar el correcto arranque del contenedor: $ docker logs mirundeck

version: "2"

services:
    rundeck:
        container_name:     mirundeck
        image:              rundeck/rundeck:5.1.0
        environment:
            # Esta URL es en la que se ofrece servicio (PUBLICO)
            # Por defecto se ofrece la URL: http://127.0.0.1:440
            # En nuestro caso, al tener en el host una ip de una vpn a la que no tenemos acceso desde cada,
            # usámos una IP Publica que amazon nos suministra y que sacamos de: 
            #  $ curl ifconfig.me
            RUNDECK_GRAILS_URL: "http://34.241.119.71:80"
            # En el caso de Amazon... y en otros clouds, tenemos un firewall de red que bloquea las comunicaciones
            # Hay que abrir el puerto (en nuestro caso, deshabilitaremos el forewall porque vamos a montar muchas apps) 
            # EN UN ENTORNO REAL NI DE COÑA !!!
        volumes:
                              - /home/ubuntu/environment/data/rundeck:/home/rundeck/server/data
        ports:
                              - 80:4440
